CREATE TABLE PAYMENT(
        ID NUMBER(10) NOT NULL,
        EMPLOYEE_ID NUMBER(10) NOT NULL,
        PAYMENT_DATE DATE NOT NULL,
        COMP_FREQUENCY NUMBER(10) NOT NULL,
        START_DATE DATE NOT NULL,
        END_DATE DATE NOT NULL,
		HOURS_OR_DAYS_WORKED NUMBER(3) NOT NULL,
		EARNINGS_YEAR_TO_DATE NUMBER(7) NOT NULL,
		EARNINGS NUMBER(5) NOT NULL,
		COMPENSATION NUMBER(5) NOT NULL,
        CONSTRAINT PAYMENT_PK PRIMARY KEY (ID)
		);

CREATE TABLE EMPLOYEE(
        ID NUMBER(10) NOT NULL,
        SERVICE_CENTER_ID NUMBER(10) NOT NULL,
        NAME VARCHAR(20) NOT NULL,
        ADDRESS VARCHAR(20) NOT NULL,
        EMAIL VARCHAR(20) NOT NULL,
		PHONE NUMBER(10) NOT NULL,
        FREQUENCY VARCHAR(10) NOT NULL,
        ROLE VARCHAR(20) NOT NULL,
		WAGES NUMBER(3) NOT NULL,
        START_DATE DATE NOT NULL,
        CONSTRAINT EMPLOYEE_PK PRIMARY KEY (ID)
		);

CREATE TABLE CAR(
        PLATE_NUMBER NUMBER(10) NOT NULL,
        CAR_TYPE_ID NUMBER(10) NOT NULL,
        CUSTOMER_ID NUMBER(10) NOT NULL,
        LAST_SERVICE_DATE DATE NOT NULL,
        LAST_SERVICE_MILEAGE NUMBER(10) NOT NULL,
        LAST_SERVICE_TYPE VARCHAR(20) NOT NULL,
        CONSTRAINT CAR_PK PRIMARY KEY (PLATE_NUMBER)
		);
		
CREATE TABLE CAR_TYPE(
        ID NUMBER(10) NOT NULL,
        MAKE VARCHAR(10) NOT NULL,
        MODEL VARCHAR(10) NOT NULL,
        YEAR NUMBER(4) NOT NULL,
        CONSTRAINT CAR_TYPE_PK PRIMARY KEY (ID)
  		);

CREATE TABLE CUSTOMER(
        ID NUMBER(10) NOT NULL,
        NAME VARCHAR(20) NOT NULL,
        ADDRESS VARCHAR(20) NOT NULL,
        EMAIL VARCHAR(20) NOT NULL,
		PHONE_NUMBER NUMBER(10) NOT NULL,
        CONSTRAINT CUSTOMER_PK PRIMARY KEY (ID)
		);
		
		
ALTER TABLE PAYMENT ADD CONSTRAINT PAYMENT_FK_EMPLOYEE_ID
    FOREIGN KEY(SERVICE_CENTER_ID) 
	REFERENCES SERVICE_CENTER(ID);

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_FK_SERVICE_CENTER_ID 
	FOREIGN KEY(SERVICE_CENTER_ID) 
	REFERENCES SERVICE_CENTER(ID);

ALTER TABLE CAR ADD CONSTRAINT CAR_FK_CAR_TYPE_ID 
	FOREIGN KEY(CAR_TYPE_ID) 
	REFERENCES CAR_TYPE(ID);

ALTER TABLE CAR ADD CONSTRAINT CAR_FK_CUSTOMER_ID 
	FOREIGN KEY(CUSTOMER_ID) 
	REFERENCES CUSTOMER(ID);