-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2018-10-16 03:22:47.777

-- foreign keys
ALTER TABLE BASIC_SERVICE
    DROP CONSTRAINT FK_BASIC_SERVICE_CHARGE_RATE;

ALTER TABLE BSXMS
    DROP CONSTRAINT FK_BSOXMSO_BASIC_SERVICE;

ALTER TABLE BSXMS
    DROP CONSTRAINT FK_BSXMS_MAINTENANCE_SERVICE;

ALTER TABLE BSXRS
    DROP CONSTRAINT FK_BSXRSO_BASIC_SERVICE;

ALTER TABLE BSXRS
    DROP CONSTRAINT FK_BSXRS_REPAIR_SERVICE;

ALTER TABLE CAUSEXREPAIR_SERVICE
    DROP CONSTRAINT FK_CAUSEXREPAIR_SERVICE_CAUSE;

ALTER TABLE CAUSEXREPAIR_SERVICE
    DROP CONSTRAINT FK_CAUSEXREPAIR_SERVICE_RS;

ALTER TABLE CUSTOMERXINVOICE
    DROP CONSTRAINT FK_CUSTOMERXINVOICE_CUSTOMER;

ALTER TABLE CUSTOMERXINVOICE
    DROP CONSTRAINT FK_CUSTOMERXINVOICE_INVOICE;

ALTER TABLE MAINTENANCE_SERVICE
    DROP CONSTRAINT FK_MAINT_SERVI_OFFE_CAR_TYPE;

ALTER TABLE PARTXBASIC_SERVICE
    DROP CONSTRAINT FK_PARTXBASIC_SERVICE_BS;

ALTER TABLE WORK_APPOINTMENTXINVOICE
    DROP CONSTRAINT FK_WORK_APPOINTMENTXINVOICE_I;

ALTER TABLE WORK_APPOINTMENTXINVOICE
    DROP CONSTRAINT FK_WORK_APPOINTMENTXINVOICE_WA;

ALTER TABLE PARTXBASIC_SERVICE
    DROP CONSTRAINT PARTXBASIC_SERVICE_PART;

-- tables
DROP TABLE BASIC_SERVICE;

DROP TABLE BSXMS;

DROP TABLE BSXRS;

DROP TABLE CAR_TYPE;

DROP TABLE CAUSE;

DROP TABLE CAUSEXREPAIR_SERVICE;

DROP TABLE CHARGE_RATE;

DROP TABLE CUSTOMER;

DROP TABLE CUSTOMERXINVOICE;

DROP TABLE INVOICE;

DROP TABLE MAINTENANCE_SERVICE;

DROP TABLE PART;

DROP TABLE PARTXBASIC_SERVICE;

DROP TABLE REPAIR_SERVICE;

DROP TABLE WORK_APPOINTMENT;

DROP TABLE WORK_APPOINTMENTXINVOICE;

-- End of file.

