-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2018-10-16 03:22:47.777

-- tables
-- Table: BASIC_SERVICE
CREATE TABLE BASIC_SERVICE (
    ID number(10,0)  NOT NULL,
    EXPECTED_HOURS number(10,0)  NOT NULL,
    WARRANTY_PERIOD number(10,0)  NOT NULL,
    CHARGE_RATE_ID number(10,0)  NOT NULL,
    CONSTRAINT BASIC_SERVICE_pk PRIMARY KEY (ID)
) ;

-- Table: BSXMS
CREATE TABLE BSXMS (
    BASIC_SERVICE_ID number(10,0)  NOT NULL,
    MAINTENANCE_SERVICE_ID number(10,0)  NOT NULL,
    CONSTRAINT BSXMS_pk PRIMARY KEY (BASIC_SERVICE_ID,MAINTENANCE_SERVICE_ID)
) ;

-- Table: BSXRS
CREATE TABLE BSXRS (
    BASIC_SERVICE_ID number(10,0)  NOT NULL,
    REPAIR_SERVICE_ID number(10,0)  NOT NULL,
    CONSTRAINT BSXRS_pk PRIMARY KEY (BASIC_SERVICE_ID,REPAIR_SERVICE_ID)
) ;

-- Table: CAR_TYPE
CREATE TABLE CAR_TYPE (
    ID number(10,0)  NOT NULL,
    MAKE varchar2(20)  NOT NULL,
    MODEL varchar2(20)  NOT NULL,
    YEAR number(4,0)  NOT NULL,
    CONSTRAINT CAR_TYPE_pk PRIMARY KEY (ID)
) ;

-- Table: CAUSE
CREATE TABLE CAUSE (
    ID number(10,0)  NOT NULL,
    DEFINITION varchar2(20)  NOT NULL,
    CONSTRAINT CAUSE_pk PRIMARY KEY (ID)
) ;

-- Table: CAUSEXREPAIR_SERVICE
CREATE TABLE CAUSEXREPAIR_SERVICE (
    CAUSE_ID number(10,0)  NOT NULL,
    REPAIR_SERVICE_ID number(10,0)  NOT NULL,
    CONSTRAINT CAUSEXREPAIR_SERVICE_pk PRIMARY KEY (CAUSE_ID,REPAIR_SERVICE_ID)
) ;

-- Table: CHARGE_RATE
CREATE TABLE CHARGE_RATE (
    ID number(10,0)  NOT NULL,
    CONSTRAINT CHARGE_RATE_pk PRIMARY KEY (ID)
) ;

-- Table: CUSTOMER
CREATE TABLE CUSTOMER (
    ID number(10,0)  NOT NULL,
    CONSTRAINT CUSTOMER_pk PRIMARY KEY (ID)
) ;

-- Table: CUSTOMERXINVOICE
CREATE TABLE CUSTOMERXINVOICE (
    CUSTOMER_ID number(10,0)  NOT NULL,
    INVOICE_ID number(10,0)  NOT NULL,
    CONSTRAINT CUSTOMERXINVOICE_pk PRIMARY KEY (CUSTOMER_ID,INVOICE_ID)
) ;

-- Table: INVOICE
CREATE TABLE INVOICE (
    ID number(10,0)  NOT NULL,
    "DATE" date  NOT NULL,
    TOTAL_COST number(10,2)  NOT NULL,
    STATUS varchar2(20)  NOT NULL,
    CONSTRAINT INVOICE_pk PRIMARY KEY (ID)
) ;

-- Table: MAINTENANCE_SERVICE
CREATE TABLE MAINTENANCE_SERVICE (
    ID number(10,0)  NOT NULL,
    TYPE varchar2(20)  NOT NULL,
    MILEAGE number(10,0)  NOT NULL,
    NUMBER_OF_MONTHS number(10,0)  NOT NULL,
    CAR_TYPE_ID number(10,0)  NOT NULL,
    CONSTRAINT MAINTENANCE_SERVICE_pk PRIMARY KEY (ID)
) ;

-- Table: PART
CREATE TABLE PART (
    ID number(10,0)  NOT NULL,
    CONSTRAINT PART_pk PRIMARY KEY (ID)
) ;

-- Table: PARTXBASIC_SERVICE
CREATE TABLE PARTXBASIC_SERVICE (
    BASIC_SERVICE_ID number(10,0)  NOT NULL,
    PART_ID number(10,0)  NOT NULL,
    CONSTRAINT PARTXBASIC_SERVICE_pk PRIMARY KEY (BASIC_SERVICE_ID,PART_ID)
) ;

-- Table: REPAIR_SERVICE
CREATE TABLE REPAIR_SERVICE (
    ID number(10,0)  NOT NULL,
    PROBLEM varchar2(20)  NOT NULL,
    CONSTRAINT REPAIR_SERVICE_pk PRIMARY KEY (ID)
) ;

-- Table: WORK_APPOINTMENT
CREATE TABLE WORK_APPOINTMENT (
    ID number(10,0)  NOT NULL,
    CONSTRAINT WORK_APPOINTMENT_pk PRIMARY KEY (ID)
) ;

-- Table: WORK_APPOINTMENTXINVOICE
CREATE TABLE WORK_APPOINTMENTXINVOICE (
    WORK_APPOINTMENT_ID number(10,0)  NOT NULL,
    INVOICE_ID number(10,0)  NOT NULL,
    CONSTRAINT WORK_APPOINTMENTXINVOICE_pk PRIMARY KEY (WORK_APPOINTMENT_ID,INVOICE_ID)
) ;

-- foreign keys
-- Reference: FK_BASIC_SERVICE_CHARGE_RATE (table: BASIC_SERVICE)
ALTER TABLE BASIC_SERVICE ADD CONSTRAINT FK_BASIC_SERVICE_CHARGE_RATE
    FOREIGN KEY (CHARGE_RATE_ID)
    REFERENCES CHARGE_RATE (ID);

-- Reference: FK_BSOXMSO_BASIC_SERVICE (table: BSXMS)
ALTER TABLE BSXMS ADD CONSTRAINT FK_BSOXMSO_BASIC_SERVICE
    FOREIGN KEY (BASIC_SERVICE_ID)
    REFERENCES BASIC_SERVICE (ID);

-- Reference: FK_BSXMS_MAINTENANCE_SERVICE (table: BSXMS)
ALTER TABLE BSXMS ADD CONSTRAINT FK_BSXMS_MAINTENANCE_SERVICE
    FOREIGN KEY (MAINTENANCE_SERVICE_ID)
    REFERENCES MAINTENANCE_SERVICE (ID);

-- Reference: FK_BSXRSO_BASIC_SERVICE (table: BSXRS)
ALTER TABLE BSXRS ADD CONSTRAINT FK_BSXRSO_BASIC_SERVICE
    FOREIGN KEY (BASIC_SERVICE_ID)
    REFERENCES BASIC_SERVICE (ID);

-- Reference: FK_BSXRS_REPAIR_SERVICE (table: BSXRS)
ALTER TABLE BSXRS ADD CONSTRAINT FK_BSXRS_REPAIR_SERVICE
    FOREIGN KEY (REPAIR_SERVICE_ID)
    REFERENCES REPAIR_SERVICE (ID);

-- Reference: FK_CAUSEXREPAIR_SERVICE_CAUSE (table: CAUSEXREPAIR_SERVICE)
ALTER TABLE CAUSEXREPAIR_SERVICE ADD CONSTRAINT FK_CAUSEXREPAIR_SERVICE_CAUSE
    FOREIGN KEY (CAUSE_ID)
    REFERENCES CAUSE (ID);

-- Reference: FK_CAUSEXREPAIR_SERVICE_RS (table: CAUSEXREPAIR_SERVICE)
ALTER TABLE CAUSEXREPAIR_SERVICE ADD CONSTRAINT FK_CAUSEXREPAIR_SERVICE_RS
    FOREIGN KEY (REPAIR_SERVICE_ID)
    REFERENCES REPAIR_SERVICE (ID);

-- Reference: FK_CUSTOMERXINVOICE_CUSTOMER (table: CUSTOMERXINVOICE)
ALTER TABLE CUSTOMERXINVOICE ADD CONSTRAINT FK_CUSTOMERXINVOICE_CUSTOMER
    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMER (ID);

-- Reference: FK_CUSTOMERXINVOICE_INVOICE (table: CUSTOMERXINVOICE)
ALTER TABLE CUSTOMERXINVOICE ADD CONSTRAINT FK_CUSTOMERXINVOICE_INVOICE
    FOREIGN KEY (INVOICE_ID)
    REFERENCES INVOICE (ID);

-- Reference: FK_MAINT_SERVI_OFFE_CAR_TYPE (table: MAINTENANCE_SERVICE)
ALTER TABLE MAINTENANCE_SERVICE ADD CONSTRAINT FK_MAINT_SERVI_OFFE_CAR_TYPE
    FOREIGN KEY (CAR_TYPE_ID)
    REFERENCES CAR_TYPE (ID);

-- Reference: FK_PARTXBASIC_SERVICE_BS (table: PARTXBASIC_SERVICE)
ALTER TABLE PARTXBASIC_SERVICE ADD CONSTRAINT FK_PARTXBASIC_SERVICE_BS
    FOREIGN KEY (BASIC_SERVICE_ID)
    REFERENCES BASIC_SERVICE (ID);

-- Reference: FK_WORK_APPOINTMENTXINVOICE_I (table: WORK_APPOINTMENTXINVOICE)
ALTER TABLE WORK_APPOINTMENTXINVOICE ADD CONSTRAINT FK_WORK_APPOINTMENTXINVOICE_I
    FOREIGN KEY (INVOICE_ID)
    REFERENCES INVOICE (ID);

-- Reference: FK_WORK_APPOINTMENTXINVOICE_WA (table: WORK_APPOINTMENTXINVOICE)
ALTER TABLE WORK_APPOINTMENTXINVOICE ADD CONSTRAINT FK_WORK_APPOINTMENTXINVOICE_WA
    FOREIGN KEY (WORK_APPOINTMENT_ID)
    REFERENCES WORK_APPOINTMENT (ID);

-- Reference: PARTXBASIC_SERVICE_PART (table: PARTXBASIC_SERVICE)
ALTER TABLE PARTXBASIC_SERVICE ADD CONSTRAINT PARTXBASIC_SERVICE_PART
    FOREIGN KEY (PART_ID)
    REFERENCES PART (ID);

-- End of file.

