DROP TABLE JRIVERA5.CAR_TYPE;

CREATE TABLE JRIVERA5.CAR_TYPE (
		ID NUMBER(10 , 0),
		MAKE VARCHAR2(10),
		MODEL VARCHAR2(10),
		YEAR NUMBER(4 , 0),
    	CONSTRAINT CAR_TYPE_PK PRIMARY KEY(ID)
	);

--Service_Offering_Main_Serv (sid: integer, type: String, mileage: integer, number_of_months: integer, cid: integer) 

DROP TABLE JRIVERA5.SERV_OFF_MAIN_SERV;

CREATE TABLE JRIVERA5.SERV_OFF_MAIN_SERV(
		SID NUMBER(10),
		TYPE VARCHAR2(10),
		MILEAGE NUMBER(10),
		NUM_OF_MONTH NUMBER(10),
		CID NUMBER(10),
		CONSTRAINT SERV_OFF_MAIN_SERV_PK PRIMARY KEY(SID),
		CONSTRAINT FK_CAR_TYPE FOREIGN KEY(CID) REFERENCES JRIVERA5.CAR_TYPE (ID)

);

GRANT ALL ON JRIVERA5.CAR_TYPE TO KGUPTA7; 
GRANT ALL ON JRIVERA5.SERV_OFF_MAIN_SERV TO KGUPTA7; 
GRANT ALL ON JRIVERA5.CAR_TYPE TO atripat6; 
GRANT ALL ON JRIVERA5.SERV_OFF_MAIN_SERV TO atripat6; 
GRANT ALL ON JRIVERA5.CAR_TYPE TO vmaskhu; 
GRANT ALL ON JRIVERA5.SERV_OFF_MAIN_SERV TO vmaskhu; 


